from enum import Enum


class EventType(str, Enum):
    MARKET_EVENT = "MARKET_EVENT"
    SPENDING_EVENT = "SPENDING_EVENT"
    TASK_EVENT = "TASK_EVENT"
    PORTFOLIO_EVENT = "PORTFOLIO_EVENT"
    TRADE_EVENT = "TRADE_EVENT"
    GOAL_EVENT = "GOAL_EVENT"
    NOTIFICATION_EVENT = "NOTIFICATION_EVENT"
